# config/config.yaml

# USER: Update these paths to point to your data
fastq_dir: "data"
output_dir: "results"
log_dir: "logs"


# Reference files
reference:
  fasta: "resources/GRCh38.primary_assembly.genome.fa"
  gtf: "resources/gencode.v44.primary_assembly.annotation.gtf"
  dbsnp: "resources/Homo_sapiens_assembly38.dbsnp138.vcf"
  mills_indels: "resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  star_index_dir: "resources/star_hg38_index"

# Chromosomes to include in analysis
chromosomes: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10",
              "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19",
              "chr20", "chr21", "chr22", "chrX", "chrY"]

# Filters for VariantFiltration
variant_filters:
  name: "FS_filter"
  expression: "FS > 30.0 || QD < 5.0"


# Resources (Memory in GB, Threads)
resources:
  join_genotyping:
    memory: 64 # GB
    threads: 4
